In [1]:
import numpy as np
import pandas as pd
import nibabel as nib
from nilearn import datasets
from nilearn.image import new_img_like
from nilearn.maskers import NiftiMasker

In [5]:
sbc_img = nib.load(r'D:\course\fMRI_processing_May2024\CONN\groups\conn_g\results\firstlevel\SBC_01\BETA_Subject001_Condition001_Source001.nii')

In [7]:
data = sbc_img.get_fdata()

In [9]:
data.shape

(91, 109, 91)

In [11]:
abs_data = np.abs(data)

In [13]:
data.max()

1.4036146402359009

In [16]:
data.min()

-0.5720938444137573

In [20]:
abs_data.min()

0.0

In [23]:
abs_data.max()

1.4036146402359009

In [25]:
value_thr = 0.35 * abs_data.max()

In [27]:
value_thr

0.4912651240825653

In [29]:
aal = datasets.fetch_atlas_aal(version = "SPM12")

In [31]:
aal_img = nib.load(aal.maps)

In [77]:
aal.labels

['Precentral_L',
 'Precentral_R',
 'Frontal_Sup_L',
 'Frontal_Sup_R',
 'Frontal_Sup_Orb_L',
 'Frontal_Sup_Orb_R',
 'Frontal_Mid_L',
 'Frontal_Mid_R',
 'Frontal_Mid_Orb_L',
 'Frontal_Mid_Orb_R',
 'Frontal_Inf_Oper_L',
 'Frontal_Inf_Oper_R',
 'Frontal_Inf_Tri_L',
 'Frontal_Inf_Tri_R',
 'Frontal_Inf_Orb_L',
 'Frontal_Inf_Orb_R',
 'Rolandic_Oper_L',
 'Rolandic_Oper_R',
 'Supp_Motor_Area_L',
 'Supp_Motor_Area_R',
 'Olfactory_L',
 'Olfactory_R',
 'Frontal_Sup_Medial_L',
 'Frontal_Sup_Medial_R',
 'Frontal_Med_Orb_L',
 'Frontal_Med_Orb_R',
 'Rectus_L',
 'Rectus_R',
 'Insula_L',
 'Insula_R',
 'Cingulum_Ant_L',
 'Cingulum_Ant_R',
 'Cingulum_Mid_L',
 'Cingulum_Mid_R',
 'Cingulum_Post_L',
 'Cingulum_Post_R',
 'Hippocampus_L',
 'Hippocampus_R',
 'ParaHippocampal_L',
 'ParaHippocampal_R',
 'Amygdala_L',
 'Amygdala_R',
 'Calcarine_L',
 'Calcarine_R',
 'Cuneus_L',
 'Cuneus_R',
 'Lingual_L',
 'Lingual_R',
 'Occipital_Sup_L',
 'Occipital_Sup_R',
 'Occipital_Mid_L',
 'Occipital_Mid_R',
 'Occipital_Inf_L'

In [35]:
label_ind = aal.labels.index('Hippocampus_L')

In [37]:
region_index = aal.indices[label_ind]

In [39]:
region_index

'4101'

In [41]:
region_mask = (aal_img.get_fdata() == float(region_index))

In [43]:
region_img = new_img_like(aal_img, region_mask)

In [47]:
masker = NiftiMasker(mask_img = region_img, target_affine = sbc_img.affine)

In [49]:
value_of_each_voxel = masker.fit_transform(sbc_img)

In [53]:
value_of_each_voxel

array([[ 1.51261523e-01,  3.02291930e-01,  7.20915124e-02,
         9.78170410e-02,  1.04728222e-01,  7.07436576e-02,
         8.86018500e-02,  9.91294160e-02,  1.61123931e-01,
         1.28359869e-01,  9.92504433e-02,  6.99986666e-02,
         6.49674162e-02,  5.88625558e-02, -6.41245628e-03,
        -1.85604952e-02,  4.74437214e-02,  1.45637140e-01,
         2.88821012e-01,  4.45602596e-01, -3.09402738e-02,
         5.25920570e-01,  5.16648054e-01,  2.57289899e-03,
        -3.36138755e-02, -3.18197384e-02, -3.12984292e-03,
         1.06163852e-01,  4.12883684e-02,  1.60524864e-02,
         1.06756194e-02,  3.55923884e-02,  1.44979522e-01,
         9.60861966e-02,  4.78655212e-02, -7.68237794e-03,
        -1.15100117e-02,  1.70273371e-02, -4.04757597e-02,
        -3.58621515e-02, -6.95211217e-02,  3.31133492e-02,
         2.60398448e-01,  3.55467439e-01,  4.19823170e-01,
         4.31530744e-01,  1.68003887e-01,  3.00151616e-01,
         4.38887954e-01,  5.40001512e-01,  5.02992034e-0

In [55]:
voxels = np.sum(value_of_each_voxel >= value_thr)

In [59]:
voxels

14

In [65]:
voxel_count_thr = round(0.25 * value_of_each_voxel.shape[1])

In [67]:
voxel_count_thr

233

In [69]:
aal = datasets.fetch_atlas_aal(version = 'SPM12')
aal_img = nib.load(aal.maps)

In [71]:
sbc_img = nib.load(r'D:\course\fMRI_processing_May2024\CONN\groups\conn_g\results\firstlevel\SBC_01\BETA_Subject001_Condition001_Source001.nii')
data = sbc_img.get_fdata()
abs_data = np.abs(data)
data.shape

(91, 109, 91)

In [73]:
value_thresh = 0.35 * np.max(abs_data)
value_thresh

0.4912651240825653

In [79]:
labels_indices = dict(zip(aal.labels, aal.indices))

In [81]:
labels_indices

{'Precentral_L': '2001',
 'Precentral_R': '2002',
 'Frontal_Sup_L': '2101',
 'Frontal_Sup_R': '2102',
 'Frontal_Sup_Orb_L': '2111',
 'Frontal_Sup_Orb_R': '2112',
 'Frontal_Mid_L': '2201',
 'Frontal_Mid_R': '2202',
 'Frontal_Mid_Orb_L': '2211',
 'Frontal_Mid_Orb_R': '2212',
 'Frontal_Inf_Oper_L': '2301',
 'Frontal_Inf_Oper_R': '2302',
 'Frontal_Inf_Tri_L': '2311',
 'Frontal_Inf_Tri_R': '2312',
 'Frontal_Inf_Orb_L': '2321',
 'Frontal_Inf_Orb_R': '2322',
 'Rolandic_Oper_L': '2331',
 'Rolandic_Oper_R': '2332',
 'Supp_Motor_Area_L': '2401',
 'Supp_Motor_Area_R': '2402',
 'Olfactory_L': '2501',
 'Olfactory_R': '2502',
 'Frontal_Sup_Medial_L': '2601',
 'Frontal_Sup_Medial_R': '2602',
 'Frontal_Med_Orb_L': '2611',
 'Frontal_Med_Orb_R': '2612',
 'Rectus_L': '2701',
 'Rectus_R': '2702',
 'Insula_L': '3001',
 'Insula_R': '3002',
 'Cingulum_Ant_L': '4001',
 'Cingulum_Ant_R': '4002',
 'Cingulum_Mid_L': '4011',
 'Cingulum_Mid_R': '4012',
 'Cingulum_Post_L': '4021',
 'Cingulum_Post_R': '4022',
 'Hipp

In [87]:
related_roi = []
for label, index in labels_indices.items():
    region_mask = (aal_img.get_fdata() == float(index))
    region_img = new_img_like(aal_img, region_mask)
    masker = NiftiMasker(mask_img = region_img, target_affine = sbc_img.affine)
    value_of_each_voxel = np.abs(masker.fit_transform(sbc_img))
    count_voxel  = np.sum(value_of_each_voxel >= value_thresh)
    voxel_count_thr = round(0.20 * value_of_each_voxel.shape[1])
    if count_voxel >= voxel_count_thr:
        related_roi.append(label)

In [85]:
value_of_each_voxel.shape[1]

932

In [89]:
related_roi

['Frontal_Med_Orb_L', 'Frontal_Med_Orb_R', 'Rectus_L', 'Rectus_R']

In [125]:
from scipy.io import loadmat

In [127]:
mat_data = loadmat(r'D:\course\fMRI_processing_May2024\CONN\groups\conn_g\results\firstlevel\RRC_01\resultsROI_Subject001_Condition001.mat')

In [129]:
mat_data

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Thu Jul  4 11:46:42 2024',
 '__version__': '1.0',
 '__globals__': [],
 'names': array([[array(['networks.DefaultMode.MPFC (1,55,-3)'], dtype='<U35'),
         array(['networks.DefaultMode.LP (L) (-39,-77,33)'], dtype='<U40'),
         array(['networks.DefaultMode.LP (R) (47,-67,29)'], dtype='<U39'),
         array(['networks.DefaultMode.PCC (1,-61,38)'], dtype='<U35')]],
       dtype=object),
 'xyz': array([[array([[ 1.11292719, 55.3268945 , -2.88558692]]),
         array([[-38.91066282, -76.87223823,  33.13544669]]),
         array([[ 47.18401207, -66.60482655,  28.72699849]]),
         array([[  0.63025036, -60.9828264 ,  38.13697496]])]],
       dtype=object),
 'Z': array([[       nan, 0.44102669, 0.4893225 , 0.47067402],
        [0.44102669,        nan, 0.84256263, 0.67657577],
        [0.4893225 , 0.84256263,        nan, 0.55826174],
        [0.47067402, 0.67657577, 0.55826174,        nan]]),
 'DOF': array([[115.

In [131]:
Z = mat_data['Z']

In [133]:
Z

array([[       nan, 0.44102669, 0.4893225 , 0.47067402],
       [0.44102669,        nan, 0.84256263, 0.67657577],
       [0.4893225 , 0.84256263,        nan, 0.55826174],
       [0.47067402, 0.67657577, 0.55826174,        nan]])

In [137]:
mat_data['names']

array([[array(['networks.DefaultMode.MPFC (1,55,-3)'], dtype='<U35'),
        array(['networks.DefaultMode.LP (L) (-39,-77,33)'], dtype='<U40'),
        array(['networks.DefaultMode.LP (R) (47,-67,29)'], dtype='<U39'),
        array(['networks.DefaultMode.PCC (1,-61,38)'], dtype='<U35')]],
      dtype=object)

In [149]:
mat_data['names'][0]

array([array(['networks.DefaultMode.MPFC (1,55,-3)'], dtype='<U35'),
       array(['networks.DefaultMode.LP (L) (-39,-77,33)'], dtype='<U40'),
       array(['networks.DefaultMode.LP (R) (47,-67,29)'], dtype='<U39'),
       array(['networks.DefaultMode.PCC (1,-61,38)'], dtype='<U35')],
      dtype=object)

In [165]:
columns_name = [name[0] for name in mat_data['names'][0]]

In [173]:
columns_name

['networks.DefaultMode.MPFC (1,55,-3)',
 'networks.DefaultMode.LP (L) (-39,-77,33)',
 'networks.DefaultMode.LP (R) (47,-67,29)',
 'networks.DefaultMode.PCC (1,-61,38)']

In [177]:
Z_df = pd.DataFrame(Z, columns = columns_name,  index = columns_name)

In [179]:
Z_df

networks.DefaultMode.MPFC (1,55,-3)  \
networks.DefaultMode.MPFC (1,55,-3)                                       NaN   
networks.DefaultMode.LP (L) (-39,-77,33)                             0.441027   
networks.DefaultMode.LP (R) (47,-67,29)                              0.489323   
networks.DefaultMode.PCC (1,-61,38)                                  0.470674   

                                          networks.DefaultMode.LP (L) (-39,-77,33)  \
networks.DefaultMode.MPFC (1,55,-3)                                       0.441027   
networks.DefaultMode.LP (L) (-39,-77,33)                                       NaN   
networks.DefaultMode.LP (R) (47,-67,29)                                   0.842563   
networks.DefaultMode.PCC (1,-61,38)                                       0.676576   

                                          networks.DefaultMode.LP (R) (47,-67,29)  \
networks.DefaultMode.MPFC (1,55,-3)                                      0.489323   
networks.DefaultMode.LP (L) (-39,-77,33)                                 0.842563   
networks.DefaultMode.LP (R) (47,-67,29)                                       NaN   
networks.DefaultMode.PCC (1,-61,38)                                      0.558262   

                                          networks.DefaultMode.PCC (1,-61,38)  
networks.DefaultMode.MPFC (1,55,-3)                                  0.470674  
networks.DefaultMode.LP (L) (-39,-77,33)                             0.676576  
networks.DefaultMode.LP (R) (47,-67,29)                              0.558262  
networks.DefaultMode.PCC (1,-61,38)                                       NaN